### ISSUE TITLE
Create a Svelte project without kit

### ISSUE THREAD

**Issue by jzillmann** [sveltejs/cli#260] opened 2024-11-02 01:36 UTC
I would like to setup a project using Svelte, without using Kit!

Is that something you consider adding to the cli ?

**Comment by benmccann** [comment] 2024-11-02 01:49
Closing as duplicate of https://github.com/sveltejs/cli/issues/168

Can you share what your usecase is though?

**Closed by benmccann** 2024-11-02 01:49 UTC

**Comment by jzillmann** [comment] 2024-11-04 02:45
Lot of times I just use plain svelte. Usually I already have a backend, e.g. tauri.
Still could use kit, but it doesn't compel to me for some reason

**Comment by benmccann** [comment] 2024-11-04 02:49
What router do you use in that case?

**Comment by jzillmann** [comment] 2024-11-04 15:00
So far...
- none (e.g. for pure tauri apps)
- `svelte-routing`
- `svelte-pathfinder`
