### ISSUE TITLE
Add jsconfig.json even for people not wanting any type checking

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/cli#267] opened 2024-11-03 11:24 UTC
Right now the `jsconfig.json` is omitted if people want no type checking at all. This has a few unwanted side effects
- intellisense isn't as good anymore. The VS Code extension will make the whole thing a inferred project which has some limitations
- stuff like aliases (`$lib` for example) doesn't work, in the sense of if you click on the component / import path it won't take you to the definition, because intellisense has no way of knowing how to resolve it
- other quirks like https://github.com/sveltejs/language-tools/issues/2557

For this reason, the CLI should add a jsconfig regardless, just with the type checking option turned off (i.e. `"checkJs": false`)

**Comment by manuel3108** [comment] 2024-11-04 16:29
Isn't this a duplicate of https://github.com/sveltejs/cli/issues/198 ?

**Comment by dummdidumm** [comment] 2024-11-04 23:06
Ah yeah, basically yes, though this one has the more obvious title. Closing the other in favor of this one.

**Closed** 2024-11-12 17:01 UTC
