### ISSUE TITLE
"npx sv create app" not working

### ISSUE THREAD

**Issue by ChosenDango** [sveltejs/cli#347] opened 2024-12-04 12:35 UTC
As the title says, I cannot create a new project, when i run the command it runs for a couple of seconds and then stops, no errors or anything, it does nothing.
I tried uninstalling nvm and reinstalling it again but it did not work.

https://github.com/user-attachments/assets/b98be2f5-59a7-4de0-8b6d-8f0d651dd0d8

**Comment by Conduitry** [comment] 2024-12-04 13:12
Does npx work for you for other packages?

**Comment by ChosenDango** [comment] 2024-12-04 13:22
> Does npx work for you for other packages?

yes, i just tested it using "npx tailwindcss init"

**Comment by manuel3108** [comment] 2024-12-04 17:26
Any chance #259 or #317 are happening to you?

**Comment by ChosenDango** [comment] 2024-12-04 18:40
> Any chance #259 or #317 are happening to you?

yes it's the same issue in #317, i tried running `npx sv` and `npx "sv"` and i get the same output.

here's the output of $PSVersionTable
![image](https://github.com/user-attachments/assets/826cc0ea-7820-4950-b9a8-e9cb4cde46cf)

**Comment by AdrianGonz97** [comment] 2024-12-16 18:05
@ChosenDango Check if https://github.com/sveltejs/cli/issues/317#issuecomment-2536972117 resolves your issue.

Will close this as a duplicate of #317

**Closed by AdrianGonz97** 2024-12-16 18:05 UTC
